from collections import OrderedDict
from format_sample_data import *

synthetic_data = OrderedDict([
    ("GTCTGCTTCCCTTCTAACAGTGGTCATCAAGGCGTAATCAGTGAACCGGGCGACTGTACTATGTAGTCAAAAGATCCCTAAGCTACAGAACCCACGCGCC", 0),
    ("TCACCGAAAGAGGGTTTCATCCGTAACCAGCAACAAGCTATTACCATCCTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGACGCCTTGCTGGTCTCA", 1),
    ("CGAGGTGTATTTGATCTTTGTTCGCGTTGCCAACCTCCGGATCCTTGTACTTGCCTTAGTATGGCGCATACTGCCTATATAAAACTGCTCCTTTACATCT", 0),
    ("GGCCCTGGAGGAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGACTATGCAGCAACAACCCTTAGACTCCTTTGGTTGGGACTTAGTCCAGGCCCATTC", 1),
])

gram_matrix = get_gram_matrix(synthetic_data)
print gram_matrix

labels = get_label_array(synthetic_data)
print labels
