import numpy as np
from collections import OrderedDict
from format_sample_data import *
from sklearn import svm

synthetic_data = OrderedDict([
    ("GTCTGCTTCCCTTCTAACTGTGGTCATCAAGGCGTAATCA", 0),
    ("GCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGCTAAC", 1),
])

gram_matrix = get_gram_matrix(synthetic_data)
print gram_matrix

labels = get_label_array(synthetic_data)
print "Labels:"
print labels

clf = svm.SVC(kernel='precomputed')
print clf.fit(gram_matrix, labels)
print "Prediction:"
print clf.predict(gram_matrix)

synthetic_data = OrderedDict([
    ("CTGTGCGAGTTATTGCGTGCTGGCGTGAGTCTAGAGCCCT", 0),
    ("ATACGAGATGATGATCCGCTGGCTCCTCATTTGTAAGAAC", 0),
    ("CAATCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGG", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATATGAT", 1),
])

gram_matrix = get_gram_matrix(synthetic_data)
print gram_matrix

labels = get_label_array(synthetic_data)
print "Labels:"
print labels

clf = svm.SVC(kernel='precomputed')
print clf.fit(gram_matrix, labels)
print "Prediction:"
print clf.predict(gram_matrix)

synthetic_data = OrderedDict([
    ("GTCTGCTTCCCTTCTAACTGTGGTCATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAACAGTGGTAATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAACAGTGGACATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAACCGTGGTCATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTATCAGTGGTCATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAGCAGTGGTCATCAAGGCGTAATCA", 0),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACC", 1),
])

gram_matrix = get_gram_matrix(synthetic_data)
print gram_matrix

labels = get_label_array(synthetic_data)
print "Labels:"
print labels

clf = svm.SVC(kernel='precomputed')
print clf.fit(gram_matrix, labels)
print "Prediction:"
print clf.predict(gram_matrix)

synthetic_data = OrderedDict([
    ("GTCTGCTTCCCTTCTAACTGTGGTCATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAACAGTGGACATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAACAGTGGTAATCAAGGCGTAATCA", 0),
    ("ATATTGACGGGTTTAGTCACATATACCGGGCACGCCGGTT", 0),
    ("GTCTGCTTCCCTTCTAGCAGTGGTCATCAAGGCGTAATCA", 0),
    ("AGCCGGTGCCTCGATCAAGTCGGAGGAAGTCTAGAGTTGC", 0),
    ("CGGCTTTGTATAGCCTAGGATTAGCACCGCAATCTAAAGC", 0),
    ("GTCTGGTGTGTACGCGCGAGCAGCACGTCTGGAAAGAATC", 0),
    ("GTCTGCTTCCCTTCTATCAGTGGTCATCAAGGCGTAATCA", 0),
    ("TTCATCCGTCAGGATGACAATGGGCCATGTGAACCCGTTG", 0),
    ("GTCTGCTTCCCTTCTAACCGTGGTCATCAAGGCGTAATCA", 0),
    ("CCGATGTTCGAGCTCATAGTTGAGAGATGGTCCTTACACT", 0),
    ("TGTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGC", 1),
    ("TATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATC", 1),
    ("GTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("TCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
])

gram_matrix = get_gram_matrix(synthetic_data)
print gram_matrix

labels = get_label_array(synthetic_data)
print "Labels:"
print labels

clf = svm.SVC(kernel='precomputed')
print clf.fit(gram_matrix, labels)
print "Prediction:"
print clf.predict(gram_matrix)

synthetic_data = OrderedDict([
    ("GTCTGCTTCCCTTCTAACTGTGGTCATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAACAGTGGACATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAGCAGTGGTCATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAACAGTGGTAATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTATCAGTGGTCATCAAGGCGTAATCA", 0),
    ("GTCTGCTTCCCTTCTAACCGTGGTCATCAAGGCGTAATCA", 0),
    ("GTAGTCTGGTAGTTCCAGAAGCCGCGCCCTTCTGTCACCG", 0),
    ("TTGAGATCGCTTAAGCCCTGCCTATAAGTCGCGGTAATGC", 0),
    ("GGGCCCAGTAGTCCGCGACGATAAGTAGGTACGAGCCCTA", 0),
    ("TTCATCCGTCAGGATGACAATGGGCCATGTGAACCCGTTG", 0),
    ("GTCTGGTGTGTACGCGCGAGCAGCACGTCTGGAAAGAATC", 0),
    ("CGGCTTTGTATAGCCTAGGATTAGCACCGCAATCTAAAGC", 0),
    ("ATATTGACGGGTTTAGTCACATATACCGGGCACGCCGGTT", 0),
    ("AGCCGGTGCCTCGATCAAGTCGGAGGAAGTCTAGAGTTGC", 0),
    ("GAGTACGAGTACAAAGTTTTATTGTACCGCCGGGCTCCCC", 0),
    ("GGACGGTAGGCCATTAGGTAAACATAGGATTTAACCGCGT", 0),
    ("GAGGCCATGTAGTAATGTATTTATTAGGCGAAATCCGGCA", 0),
    ("CGCGATGCTAGCATCTCAAACAATCTGGAGTACACGTTAT", 0),
    ("CCGATGTTCGAGCTCATAGTTGAGAGATGGTCCTTACACT", 0),
    ("ATGCTTGGGATCATCCCCGTCTGTCTAAATTCATTCGCAG", 0),
    ("TGCGAATGGGGCTTGAGGGAGGTGGCGCGAAGCTCTCGGG", 0),
    ("ACGAATGTGGAAACGGGAGGACATTAAAACACGAAGGATG", 0),
    ("TTCTCTCTGAGGCCGTTTACTAATATCCACTGTGTCACTC", 0),
    ("CCGAAATCCGGCCGTTCACTTCATCTTAAAAGCGCGTATG", 0),
    ("GATGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("GATTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("CATGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("GTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("TGTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("TATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGC", 1),
    ("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTT", 1),
    ("TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("TCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATC", 1),
    ("ATGCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
    ("CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("GACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATGC", 1),
    ("TTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACC", 1),
    ("TGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("TAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("GCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("CTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 1),
    ("TGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT", 1),
])

gram_matrix = get_gram_matrix(synthetic_data)
print gram_matrix

labels = get_label_array(synthetic_data)
print "Labels:"
print labels

clf = svm.SVC(kernel='precomputed')
print clf.fit(gram_matrix, labels)
print "Prediction:"
print clf.predict(gram_matrix)
